# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Command to build the project
cmd = "go build -o tmp/main ./cmd/"

# Binary to run after build
bin = "./tmp/main"

# Working directory
full_bin = "./tmp/main"

# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html"]

# Ignore these files/directories
exclude_dir = ["vendor"]

# Print build log on terminal
log = "debug"
